-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 15/04/2018 12:15:34 p. m.
-- Server version: 5.5.5-10.1.31-MariaDB
-- Client version: 4.1

DROP DATABASE IF EXISTS u207546111_motel;
CREATE DATABASE u207546111_motel
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

USE u207546111_motel;

CREATE TABLE listasprecioshabitaciones (
  CodLista varchar(3) DEFAULT NULL,
  NombreLista varchar(30) DEFAULT NULL,
  Especial varchar(2) NOT NULL DEFAULT 'NO',
  Dias varchar(255) DEFAULT NULL,
  FechaInicial date DEFAULT NULL,
  FechaFinal date DEFAULT NULL,
  HoraInicial time DEFAULT NULL,
  HoraFinal time DEFAULT NULL,
  UNIQUE INDEX UK_listasprecioshabitaciones_C (CodLista)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

CREATE TABLE servicioshabitaciones (
  CodServicioHab varchar(3) DEFAULT NULL,
  Horas int(11) DEFAULT NULL,
  Estado varchar(15) NOT NULL DEFAULT 'Activo',
  UNIQUE INDEX UK_servicioshabitaciones_CodSe (CodServicioHab)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

CREATE TABLE tiposhabitaciones (
  CodTipoHab int(11) NOT NULL AUTO_INCREMENT,
  NomTipo varchar(255) NOT NULL,
  Caracteristicas varchar(255) DEFAULT NULL,
  PRIMARY KEY (CodTipoHab),
  UNIQUE INDEX NomTipo (NomTipo)
)
ENGINE = INNODB
AUTO_INCREMENT = 43
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

CREATE TABLE habitaciones (
  CodHabitacion varchar(3) NOT NULL,
  Numero varchar(4) NOT NULL,
  CodTipoHab int(11) NOT NULL,
  Estado varchar(15) NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (CodHabitacion),
  CONSTRAINT FK_habitaciones_tiposhabitaciones_CodTipoHab FOREIGN KEY (CodTipoHab)
  REFERENCES tiposhabitaciones (CodTipoHab) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AVG_ROW_LENGTH = 2730
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

CREATE TABLE precioshabitaciones (
  CodLista varchar(3) NOT NULL,
  CodTipoHab int(11) NOT NULL,
  CodServicioHab varchar(3) DEFAULT NULL,
  ValorServicio double DEFAULT NULL,
  CONSTRAINT FK_precioshabitaciones_tiposhabitaciones_CodTipoHab FOREIGN KEY (CodTipoHab)
  REFERENCES tiposhabitaciones (CodTipoHab) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `listaprecios-precios` FOREIGN KEY (CodLista)
  REFERENCES listasprecioshabitaciones (CodLista) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `precios-servicios` FOREIGN KEY (CodServicioHab)
  REFERENCES servicioshabitaciones (CodServicioHab) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

CREATE OR REPLACE
SQL SECURITY INVOKER
VIEW vistahabitaciones
AS
SELECT
  `h`.`Numero` AS `Numero`,
  `t`.`NomTipo` AS `Nombre`,
  `h`.`Estado` AS `Estado`
FROM (`habitaciones` `h`
  JOIN `tiposhabitaciones` `t`)
WHERE (`h`.`CodTipoHab` = `t`.`CodTipoHab`);

CREATE OR REPLACE
SQL SECURITY INVOKER
VIEW vistaprecios
AS
SELECT
  `t`.`NomTipo` AS `NomTipo`,
  `s`.`Horas` AS `Horas`,
  `p`.`ValorServicio` AS `ValorServicio`
FROM (((`precioshabitaciones` `p`
  JOIN `listasprecioshabitaciones` `l`)
  JOIN `servicioshabitaciones` `s`)
  JOIN `tiposhabitaciones` `t`)
WHERE ((`p`.`CodLista` = `l`.`CodLista`) AND (`p`.`CodTipoHab` = `t`.`CodTipoHab`) AND (`s`.`CodServicioHab` = `p`.`CodServicioHab`) AND (`l`.`CodLista` = 1));